config/routes.rb
Rails.application.routes.draw do
  get 'setting/edit'

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end

  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end
  

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
  
  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :micropost_id }
  validates :micropost, presence: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base 
 has_many :favorites
 has_many :favoriting_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
  validates :location, absence: true, 
                       on: :create
  validates :location, allow_blank: true, 
                       length: { minimum: 2, maximum: 20 }, 
                       on: :update
  validates :age, allow_blank: true,
                  numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100},
                  on: :update
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  #フォローしているユーザーと自分のつぶやきを取得
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end  
  
  #お気に入り
  has_many :favorites, dependent: :destroy
  has_many :favorite_microposts,  through: :favorites, source: :micropost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in_user

  def create
    micropost = Micropost.find(params[:micropost_id])
    favorite = current_user.favorites.build(micropost: micropost)
    
    if favorite.save
      redirect_to :back, notice: "お気に入り登録しました"
    else
      redirect_to :back, notice: "お気に入り登録できませんでした。"
    end
  end

  def destroy
    favorite = current_user.favorites.find_by(micropost_id: params[:micropost_id])
    favorite.destroy if favorite
    redirect_to :back, notice: "お気に入りを解除しました。"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  def edit
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
    #@users = User.page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :followings, :followers, :favorites]
  before_action :correct_user, only: [:edit, :update]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  def show
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
   
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
 
  def update
    if @user.update(user_params)
      flash[:success] = "UPdate Profile"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def followings
    @title = "followings"
    @users = @user.following_users.page(params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "followers"
    @users = @user.follower_users.page(params[:page])
    render 'show_follow'
  end
  
  def favorites
    @microposts = @user.favorite_microposts.page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation, :location,:age)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def correct_user
    redirect_to root_path if @user != current_user
  end
  
  def favorite
    @title = 'Favorite Tweets'
    @tweet = current_user.tweets.bulid
    @feed_tweets = current_user.favorite_tweets.paginate(page: params[:page])
    render template:'about/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/favorites/_create.html.erb
<%= link_to favorites_path(tweet_id: tweet.id), remote: true, method: :post, class: 'favorite-link' do %>
  <i class="fa fa-star unfavorite-star"></i>
<% end %>

app/views/favorites/_destroy.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(tweet_id: tweet.id)), remote: true, method: :delete, class: 'favorite-link' do %>
  <i class="fa fa-star favorite-star"></i>
<% end %>

app/views/favorites/_favorite_btn.html.erb
<% if current_user.favorite?(tweet) %>
    <%= render 'favorites/destroy', tweet: tweet %>
<% else %>
    <%= render 'favorites/create', tweet: tweet %>
<% end %>

app/views/favorites/create.js.erb
$('#tweet_<%= @tweet.id %>').html('<%= escape_javascript(render("favorites/favorite_btn", tweet: @tweet)) %>')
$('#favorites').text('<%= current_user.favorites.count %>')

app/views/favorites/destroy.html.erb
$('#tweet_<%= @tweet.id %>').html('<%= escape_javascript(render("favorites/favorite_btn", tweet: @tweet)) %>');
$('#favorites').text('<%= current_user.favorites.count %>');

app/views/favorites/favorite.html.erb
<h1>Tweet</h1>

<%= render @tweet %>

<h1>Users</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
    </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  <% if micropost.favorited_by?(current_user) %>
    <%= link_to "Release Favorites", micropost_favorites_path(micropost), method: :delete %>
  <% else %>
    <%= link_to "Add Favorites", micropost_favorites_path(micropost), method: :post %>
  <% end %>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/setting/edit.html.erb
<h1>Setting#edit</h1>
<p>Find me in app/views/setting/edit.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stas.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= favorite_user_path(@user) %>">
    <strong id="favorites" class="stat">
      <%= @user.favorite_tweets.count %>
    </strong>
    favorites
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
   <div class="col-md-8">
     <h3>Micropost Feed</h3>
     <%= render 'shared/feed' %>
   </div>
   <p><%#= paginate @users %></p>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
<% end %>

app/views/tweets/_tweet.html.erb
<li>
    <%= link_to profile_image_for(tweet.user) %>
  <span class="user">
    <%= link_to tweet.user.name, tweet.user %>
  </span>
  <span class="content"><%= tweet.content %></span>
  <span id="tweet_<%= tweet.id %>">
    <%= render 'favorites/favorite_btn', tweet: tweet %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
  </span>
  <% if current_user?(tweet.user) %>
    <%= link_to "delete", tweet, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: tweet.content %>
  <% end %>
</li>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_link_btn.html.erb
<p><%= link_to 'profile', @user %> | 
<%= link_to 'following', followings_user_path(@user) %> | 
<%= link_to 'followers', followers_user_path(@user) %> | 
<%= link_to 'favorites', favorites_user_path(@user) %></p>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
 <%= link_to gravatar_for(user),user %>
 <h1><%= following_user.name %></h1>
  <span class="user"><%= link_to following.user.name, following.user %></span>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
     
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      
      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :age %>
      <%= f.text_field :age, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
     <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
     </h1>
     <ul>
      <li>Location:　<%= @user.location.present? ? @user.location : "No-Data" %></li>
      <li>age: <%=@user.age.present? ? @user.age : "No-data" %></li>
     </ul>
    </section>
    <%= render 'link_btn' %>
  </aside>
  <div class="col-md-8">
    <h3>Favorite (<%= @microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %> 
    </ol>
    <%= paginate @microposts %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
     
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
     <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
     </h1>
     <ul>
      <li>Location:　<%= @user.location.present? ? @user.location : "No-Data" %></li>
      <li>age: <%=@user.age.present? ? @user.age : "No-data" %></li>
     </ul>
    </section>
    <%= render 'link_btn' %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %> 
      </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<h1><%= @title %></h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
     <ul>
      <li>Location:　<%= @user.location.present? ? @user.location : "No-Data" %></li>
      <li>age: <%=@user.age.present? ? @user.age : "No-data" %></li>
     </ul>
    </section>
    <%= render 'link_btn' %>
  </aside>
  <div class="col-md-8">
    <ul style="list-style: none;">
      <% @users.each do |user| %>
        <li style="margin-bottom: 5px;"><%= gravatar_for user, size: 20 %><%= link_to user.name, user %></li>
      <% end %>
      <%= paginate @users %>
    </ul>
  </div>　
</div>
  